### PR TITLE
Start to make project_generator into a Python Package

### PR DESCRIPTION
**Pull request by matthewelse**
The ultimate aim of this PR is to discuss the possibility of turning this into a proper python package which can go on pip, which is installed globally on your computer, which you can then call like so:

```
project_generator build
```

as long as you're in the correct directory of course.

So far I've:
- Changed default settings to use environment variables instead of a Python file (user settings were a pain to use anyway because of submodules)
- Reorganised the code into a normal Python package format, placing different logical bits of code in different places.

If we want to continue to do this:
- [ ] We should probably switch to argparse, since it has more powerful features for command line argument parsing.
- [x] Need to add setup.py in the root directory, which defines commands that can be called directly from the command line (this is built into setuptools I think)
- [ ] We should also improve automated testing on Travis-CI

### CODE REVIEW

**Comment by matthewelse** [comment]
Currently the tests all fail because it needs to import by project_generator.builder instead of using the package locally

**Comment by 0xc0170** [comment]
+1

I'll look at the changes more soon

**Comment by matthewelse** [comment]
@0xc0170 have you had a chance to look at this?

**Comment by 0xc0170** [comment]
Yes, I finally looked at changes. I really am up for this as those settings script was not ideal. I prefer to just go to a project, run a command to build it. Like any module package system does.

I haven't pulled yet this branch, what's the status? If I can test it locally.

**Comment by matthewelse** [comment]
it should be good for you to test locally as it is - I doubt I'll have a lot of time to look at this for the next six weeks or so because I've got lots of other work to do, but I'll keep going with it

**Comment by 0xc0170** [comment]
We will have to have a closer look, it fails to start. Looks like pg=project_generator.export:main is not correct. I'll label this in progress

**Comment by 0xc0170** [comment]
@matthewelse I pulled your branch, on top of your commits, added few fixes and got now some projects building. I'll close this, and will send PR once done.

**Pull request closed without merging**
