### PR TITLE
Export - loads the definition repository or update if present

### PR DESCRIPTION
**Pull request by 0xc0170**
IAR and uVision tested for LPC1768

this is work in progress (warning! -> early alpha stage), if you want to test, need to get the repo from my branch, not the master as that one is default (this can be another option where to get the file (another github repo for example?), just sharing the target parser and how it can work with the proposal for pg definitions.

I would not send normally this, but the definitions are still not merged, so this might convince us to go ahead or adjust the current flow :)

### CODE REVIEW

**Comment by 0xc0170** [comment]
Note here (mbed related as there was one line added to pg), before merging, have to test with valinor and come up with a solution for different names between projects

**Comment by 0xc0170** [comment]
IAR, uvision and CoIDE (all definitions we use at the moment) are functional.

I might push this to a new branch, will update once I set it. To bring v0.5, we need more changes, to slow down a bit that minor numbering :-)

**Comment by 0xc0170** [comment]
Fixed building and exporting, should be working. I'll continue testing.

**Comment by 0xc0170** [comment]
I still need to fix supported targets which are used by valinor.

**Comment by 0xc0170** [comment]
To track what issues this should solve

#74 - pgen is now valid command
#67 - boards defitions are now external and pulled if not found
#62 - uvision supports lib/exe , others will follow soon

**Comment by 0xc0170** [comment]
All our supported tools have lib/exe available now :smiley:

**Comment by 0xc0170** [comment]
This branch has now all features req for v0.5. Anyone against merging this to master? 

I'll continue testing.

**Comment by matthewelse** [comment]
We should update the version in setup.py before we merge

**Pull request merged**
